### PR TITLE
feat(extras): add `symbols-outline.lua`

### PR DESCRIPTION
**Pull request by Daniel-Boll**

### CODE REVIEW

**Comment by siduck** [comment]
hi @Daniel-Boll , i think we should avoid lazyloading with keys, if the  user uses our way of defining custom mappings then it gets well documented in our cheatsheet module

**Comment by Daniel-Boll** [comment]
> hi @Daniel-Boll , i think we should avoid lazyloading with keys, if the  user uses our way of defining custom mappings then it gets well documented in our cheatsheet module

Oh, okay, it does make sense. So initially, we should lazy load by command, and then the user register it's own mappings?

**Comment by siduck** [comment]
> > hi @Daniel-Boll , i think we should avoid lazyloading with keys, if the  user uses our way of defining custom mappings then it gets well documented in our cheatsheet module
> 
> Oh, okay, it does make sense. So initially, we should lazy load by command, and then the user register it's own mappings?

yes. Also our way of lazyloading depends on the type of plugin. This plugin opens by its command so we only lazy load it by the cmd opt

**Review by siduck — APPROVED** [review]

**Comment by siduck** [comment]
btw what does config = true do?

**Comment by Daniel-Boll** [comment]
@siduck the second commmit [49c88bf](https://github.com/NvChad/example_config/pull/28/commits/49c88bf01b009d12852baa5ac474594c4bc3e59c) only contains commented code for examples of usage, if you reckon unnecessary we can remove.

**Comment by Daniel-Boll** [comment]
> btw what does config = true do?

I'm not gonna lie, I have little to no clue. I've being using this in my own config for a while this way, got it from [Folke himself](https://github.com/folke/dot/blob/6dbf11746c9d1e0883ab8db4703e29a2d85606d7/nvim/lua/plugins/coding.lua#L227).

My guess is that similarly to opts that will invoke the default configuration/setup and pass the opts into it, the `config = true` would simply call the default `config` with no setup, probably also achievable through

```lua
local spec = {
  "simrat39/symbols-outline.nvim",
  cmd = "SymbolsOutline",
  opts = {},
}

return spec
```

**Comment by Daniel-Boll** [comment]
@siduck can I merge it?

**Review by siduck — APPROVED** [review]

**Comment by lucario387** [comment]
So is tehre any reason for the Daniel-Boll branch to exist?
If no, please delete it

**Pull request merged**
